{
 "title": "CLARO/VISENT/Dashboard servidores",
 "tags": [
  "zabbix",
  "windows",
  "visent",
  "claro"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" }
  ]
 },
 "panels": [
  {
   "title": "Utilização %",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Utilização de CPU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória utilizado em %" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Métricas de CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/CPU/" },
     "minSeverity": 3,
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Utilização de RAM em GB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória usada" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Memória total" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Utilização de SWAP em GB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Espaço de Swap Usado" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Espaço de Swap total" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Partições WIndows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Porcentagem de uso em partições",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "repeat": "disks",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Filesystem .*/" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* Space utilization/" },
     "minSeverity": 3,
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interfaces de rede",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*: Bits received/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*: Bits sent/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*:: Disk read rate/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*:: Disk write rate/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}