annotations:
  catalog.cattle.io/display-name: Monitoring As a Service (MaaS) - Jack Experts
  catalog.cattle.io/os: linux
apiVersion: v2
appVersion: 0.5.0
dependencies:

- condition: zabbix.enabled
  name: zabbix
  repository: https://github.com/zabbix-community/helm-zabbix
  version: 7.0.6
- condition: grafana.enabled
  name: grafana
  repository: https://github.com/grafana/helm-charts
  version: 8.10.4
- condition: rundeck.enabled
  name: rundeck
  repository: https://eugenmayer.github.io/helm-charts
  version: 2.3.0
description: Monitoring As a Service (MaaS) - Jack Experts
icon: file://img/maas.png
name: maas
type: application
version: 0.4.1
